name: hamoney
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.4
  flutter_dotenv: ^5.0.2
  kakao_flutter_sdk_user: '>=1.4.1 <2.0.0' # 카카오 로그인
  flutter_bloc: ^8.1.2
  url_launcher: '>=6.1.10 <7.0.0'
  dio: ^4.0.6 # kakao_flutter_sdk이 이 버전을 의존하고 있다
  flutter_inappwebview: ^5.7.2+3
  fk_user_agent: ^2.1.0
  flutter_web_auth_2: ^2.1.2
  sign_in_with_apple: ^4.3.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  retrofit: '>=3.0.0 <4.0.0'
  flutter_secure_storage: ^8.0.0
  logging: ^1.1.1
  table_calendar: ^3.0.9
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: '>=2.3.0 <4.0.0'
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  retrofit_generator: '>=4.0.0 <5.0.0'


flutter:
  uses-material-design: true
  assets:
    - assets/
    - config/.env

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
